# Names to add per saint: key "M-D-Saint name" -> (masculine, feminine)
ADD = {
 "1-1-Basil the Great": ("Vasilios Vassilios Vasos Vasily Vasil Billy", "Vasiliki Vassiliki Vasilia Vaso Vasso Vasia"),
 "1-6-Theophany": ("Fanis Fotis Fotios Photios Iordanis", "Theofania Fani Fotini Foteini Photini Fotoula Ourania Rania Theopoula Peristera"),
 "1-7-John the Baptist": ("Yianni Gianni Giannakis Prodromos Johnny", "Ioanna Gianna Yianna Giannoula Joanna Joanne Joan"),
 "1-17-Anthony the Great": ("", "Antonia Tonia"),
 "1-18-Athanasios the Great": ("Thanasis Thanasi Athanasis", ""),
 "1-20-Euthymios the Great": ("Efthymios Efthymis Thymios", "Efthymia Efthimia Thymia Effie"),
 "1-25-Gregory the Theologian": ("", "Grigoria"),
 "2-10-Charalambos": ("Charalambos Haralampos Haris Charis Lambis Harry", "Charalambia Haralambia Haroula Charoula"),
 "3-25-Annunciation": ("Vaggelis Vagelis Evangelis", "Vangelio Vaggelio Evangeline"),
 "4-23-George the Great Martyr": ("Yorgos Giorgis Jorge Georges", "Georgia Giorgia Georgina Georgette Gogo"),
 "5-21-Constantine and Helen": ("Costas Costa Gus Konstantin", "Konstantina Constantina Dina Ntina Kostoula Helena Ellen Elenitsa Nitsa Lenio"),
 "6-29-Peter and Paul the Apostles": ("", "Petroula Petra Pavlina Paula Paulina"),
 "6-30-Synaxis of the Holy Apostles": ("Apostolos Apostolis Tolis", "Apostolia"),
 "7-7-Kyriaki the Great Martyr": ("", "Kyriakoula"),
 "7-20-Elijah the Prophet": ("", "Iliana Ilianna"),
 "7-26-Paraskevi the Great Martyr": ("Paraskevas", "Evi Vivi Skevi"),
 "8-15-Dormition of the Theotokos": ("Panagiotis Panayiotis Panos Marios Mario", "Panayiota Yiota Maroula Marietta Mairi Despo"),
 "8-30-Alexander the Patrician": ("", "Alexandra Aleka"),
 "10-26-Demetrios the Great Martyr": ("Mitsos Jim Demetris", "Dimitra Demetra Dimitroula Mimi Demi"),
 "11-1-Kosmas and Damian (Asian)": ("Argyris Argiris Anargyros", "Argyro Argiro Anargyri Damiani"),
 "11-8-Synaxis of Archangels Michael and Gabriel": ("Aggelos Stamatis Stamatios Taxiarchis Raphael Rafail", "Michaela Gabriella Gavriella Gavriela Angeliki Aggeliki Angela Angelina Stamatia Stamatina Matina Rafaela"),
 "11-14-Philip the Apostle": ("", "Filippa Philippa"),
 "11-25-Catherine the Great Martyr": ("", "Catherine Ekaterini Kaiti Katie Kathy"),
 "11-30-Andrew the First-Called": ("Andy", "Andriana Andrianna"),
 "12-5-Savvas the Sanctified": ("", "Savvoula"),
 "12-6-Nicholas the Wonderworker": ("", "Nikoleta Nikoletta Nicoletta Nicole Nikolina"),
 "12-9-Conception of the Theotokos by Anne": ("", "Ann Annoula"),
 "12-12-Spyridon of Trimythous": ("", "Spyridoula Spiridoula"),
 "12-15-Eleutherios": ("", "Eleftheria"),
 "12-25-Nativity of Christ": ("Christakis", "Christina Christine Kristina"),
 "12-26-Synaxis of the Theotokos": ("Emmanuel Emmanouil Manolis Manos Manuel", "Emmanouela Emmanuela Manuela"),
 "8-6-Transfiguration of the Lord": ("Sotirios Sotiris", "Sotiria Sotiroula"),
 "8-24-Eutyches the Apostle": ("Eftychios Eftychis Eftihios", "Eftychia Eftihia"),
 "9-23-Xanthippe and Polyxene": ("", "Xanthi"),
 "5-13-Glykeria": ("", "Glykeria Glikeria"),
 "2-1-Tryphon": ("Tryfon Tryphon Trifon Tryfonas", ""),
 "1-12-Tatiana": ("", "Tatiana"),
 "11-11-Victor and Stephanida": ("", "Viktoria Victoria"),
 "3-19-Chrysanthos and Daria": ("", "Chrysanthi"),
 "9-1-40 Holy Virgin Martyrs of Thrace": ("", "Penelopi"),
 "9-20-Eustace the Great Martyr": ("", "Efstathia Stathoula Theopisti Theopiste"),
 "12-27-Stephen the First Martyr": ("", "Stefania Stephania Stephanie Stefanie"),
}
ADD = {k: (m.split(), f.split()) for k, (m, f) in ADD.items()}

# Broken entries to drop (a Cyrillic/Latin mix that can never match a contact)
REMOVE = {"2-1-Tryphon": ["Tr\u0438\u0444\u043e\u043d"]}
